### ISSUE TITLE
Use logs for (or other strategy) for printing errors

### ISSUE THREAD

**Issue by mrcosta** [Trangar/html_sanitizer#1]
Hey, first of all, thanks a lot for the crate. It fits perfectly with what I'm doing.

I'm using the crate to parser a lot of files (around 6k) and I don't care if the HTML that I'm handling is not perfect, thus I don't particularly care with the output that the crate prints right now. 

I think it would be nice if this could be in somehow option or maybe put it even inside the `TagParser` struct a new property called `errors`.

myy use case: I need to print if a file was corrected parser or not for the final user and having a lot of blocks with output like:

```
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
Errors: ["Unexpected token"]
```

coming from another crate causes a lot of "noise" in the final output.

Let me know what you think and I can help with the PR. I think for now I'm going to fork and just commit the print statement, but if you think that my suggestion is reasonable I would love to help in the PR.

Kind regards

**Comment by VictorKoenders** [comment]
I honestly completely forgot I still had this crate. I've set it up on a whim because I needed it for a project and never looked at it again.

Feel free to PR anything that seems useful for you! I think it would be good if `walk` (and `internal_walk`) and `new` return `Result` instead of printing out errors and dropping it. I also want to get rid of all the `.unwrap()`s. These are breaking changes, but the crate is only 0.1.1 anyway, so bumping it to 0.2.0 is fine.
